import BatchMetric from '../common/BatchMetric'
import ConfusionMetric from '../common/ConfusionMetric'

function BatchResults({
  batchResult,
}) {
  return (
    <>
      {batchResult && (

        <section className="mt-8 rounded-2xl border border-slate-800 bg-slate-900/70 p-6 shadow-2xl">

          <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">

            <div>

              <p className="text-sm font-medium uppercase tracking-[0.2em] text-cyan-400">
                CSV Risk Assessment
              </p>

              <h3 className="mt-2 text-2xl font-bold">
                Transaction Analysis Results
              </h3>

              <p className="mt-2 text-sm text-slate-500">
                Results generated by the live XGBoost risk engine using the frozen risk threshold.
              </p>

            </div>


            <span className="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-3 py-1 text-xs font-semibold text-cyan-300">
              {batchResult.summary.total_transactions} Transactions
            </span>

          </div>


          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">

            <BatchMetric
              label="Transactions"
              value={batchResult.summary.total_transactions}
            />

            <BatchMetric
              label="Low Risk"
              value={batchResult.summary.low_risk}
              valueClass="text-emerald-400"
            />

            <BatchMetric
              label="High Risk"
              value={batchResult.summary.high_risk}
              valueClass="text-red-400"
            />

            <BatchMetric
              label="Review Required"
              value={batchResult.summary.review_required}
              valueClass="text-amber-400"
            />

          </div>


          {batchResult.evaluation && (

            <div className="mt-8 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-5">

              <div className="mb-5">

                <p className="text-sm font-semibold uppercase tracking-[0.15em] text-violet-300">
                  Ground-Truth Evaluation
                </p>

                <p className="mt-1 text-xs leading-5 text-slate-500">
                  Predictions are compared against the uploaded Class labels. Class is never used as a model input.
                </p>

              </div>


              <div className="grid gap-4 sm:grid-cols-3">

                <BatchMetric
                  label="Precision"
                  value={`${(Number(batchResult.evaluation.precision) * 100).toFixed(2)}%`}
                  valueClass="text-cyan-300"
                />

                <BatchMetric
                  label="Recall"
                  value={`${(Number(batchResult.evaluation.recall) * 100).toFixed(2)}%`}
                  valueClass="text-cyan-300"
                />

                <BatchMetric
                  label="Accuracy"
                  value={`${(Number(batchResult.evaluation.accuracy) * 100).toFixed(2)}%`}
                  valueClass="text-cyan-300"
                />

              </div>


              <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">

                <ConfusionMetric
                  label="True Positive"
                  value={batchResult.evaluation.true_positive}
                />

                <ConfusionMetric
                  label="True Negative"
                  value={batchResult.evaluation.true_negative}
                />

                <ConfusionMetric
                  label="False Positive"
                  value={batchResult.evaluation.false_positive}
                />

                <ConfusionMetric
                  label="False Negative"
                  value={batchResult.evaluation.false_negative}
                />

              </div>

            </div>

          )}

        </section>

      )}

    </>
  )
}

export default BatchResults